exclude: [_drafts, Rakefile.rb, Gemfile, Gemfile.lock]
permalink: none
input: GFM
markdown: kramdown
paginate: 5
title: artsoftheinsane - The making off...
description: The making off...
url: http://www.artsoftheinsane.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
