exclude:
  [
    _drafts,
    Rakefile.rb,
    Gemfile,
    Gemfile.lock,
    node_modules,
    package-lock.json,
    package.json,
    .ruby-version,
    .gitignore,
    css/bootstrap-grid.css,
    css/main.css,
  ]
permalink: none
input: GFM
markdown: GFM
paginate: 5
title: artsoftheinsane - Egress...
description: Egress...
url: http://www.artsoftheinsane.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
