exclude: [_drafts, bower.json, Gemfile, Gemfile.lock]
permalink: pretty
input: GFM
markdown: kramdown
paginate: 5
name: artsoftheinsane - The making off...
description: The making off...
url: http://www.artsoftheinsane.com

gems:
  - jekyll-sitemap
